version: "3.8"

services:
  db:
    restart: unless-stopped
    build:
      context: ./src/db
      dockerfile: db.Dockerfile
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./src/db/init-scripts:/docker-entrypoint-initdb.d

  api:
    build:
      context: ./src/api
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
